### ISSUE TITLE
BARAN的小站🔥🔥🔥

### ISSUE THREAD

**Issue by cxvh** [cxvh/cxvh.github.io#1]
```yml
name: BARAN的小站🔥🔥🔥
link: https://cxvh.com
avatar: https://cdn.jsdelivr.net/gh/cxvh/static@main/avatar/avatar.jpg
descr: 指尖跳动留下足迹.
```
