### ISSUE TITLE
贰猹の小窝

### ISSUE THREAD

**Issue by cxvh** [cxvh/cxvh.github.io#10]
```yml
name: 贰猹的小窝
link: https://noionion.top/
avatar: https://noionion-picture-bed.oss-cn-hangzhou.aliyuncs.com/img/head.jpg
descr: 用这生命中的每一秒，给自己一个不后悔的未来
```

**Comment by 2X-ercha** [comment]
由于小站开启图片防盗链以防盗站，导致友链头像及站点截图一并防盗链
需要更新站点信息，造成不便请谅解
```yml
name: 贰猹的小窝
link: https://noionion.top/
avatar: http://pub-noionion.oss-cn-hangzhou.aliyuncs.com/head.jpg
descr: 用这生命中的每一秒，给自己一个不后悔的未来

# 选填：
siteshot: http://pub-noionion.oss-cn-hangzhou.aliyuncs.com/noionion.top.png
```
