### ISSUE TITLE
BARAN的小站🔥

### ISSUE THREAD

**Issue by cxvh** [cxvh/cxvh.github.io#2]
```yml
link: https://cxvh.cc
avatar: https://cdn.jsdelivr.net/gh/cxvh/static@main/avatar/avatar.jpg
descr: 指尖跳动留下足迹.
```
