### ISSUE TITLE
麋鹿鲁哟

### ISSUE THREAD

**Issue by cxvh** [cxvh/cxvh.github.io#3]
```yml
name: 麋鹿鲁哟
avatar: 'https://miluluyo.github.io/vdoingBlog/img/tx.jpg'
link: 'https://www.cnblogs.com/miluluyo/'
descr: 大道至简，知易行难。
```
