### ISSUE TITLE
Loneliness

### ISSUE THREAD

**Issue by cxvh** [cxvh/cxvh.github.io#4]
```yml
name: Loneliness
avatar: 'https://blog-1303885568.cos.ap-chengdu.myqcloud.com/useImg/avat.jpg'
link: 'https://www.dingshiyi.top'
descr: 万水千山，你愿意陪我一起看吗
```
