### ISSUE TITLE
慧眼博客

### ISSUE THREAD

**Issue by cxvh** [cxvh/cxvh.github.io#5]
```yml
name: 慧眼博客
avatar: 'https://image.theeye.tech/img/15873849679911587384967991mmexport1569296865219---xinsiraa.png'
link: 'https://theeye.tech/'
descr: xinsir的个人博客
```
