### ISSUE TITLE
MYW

### ISSUE THREAD

**Issue by cxvh** [cxvh/cxvh.github.io#7]
```yml
name: MYW
link: 'https://immyw.com/'
avatar: 'https://immyw.com/img/avatar.png'
descr: '今日事,今日畢'
```
