### ISSUE TITLE
Akilarの糖果屋

### ISSUE THREAD

**Issue by cxvh** [cxvh/cxvh.github.io#8]
```yml
name: Akilarの糖果屋
link: 'https://akilar.top/'
avatar: 'https://akilar.top/img/siteicon/favicon.png'
descr: 期待您的光临！
siteshot: 'https://cdn.jsdelivr.net/gh/Akilarlxh/ScreenShot@gh-pages/akilar.top.jpg'
```
