### ISSUE TITLE
小冰博客

### ISSUE THREAD

**Issue by cxvh** [cxvh/cxvh.github.io#9]
```yml
name: 小冰博客
link: 'https://zfe.one'
avatar: 'https://zfe.space/images/headimage.png'
descr: 做个有梦想的人！
```
